package quicktfs.app;

import android.content.Context;
import android.os.AsyncTask;
import android.widget.Toast;

import java.lang.ref.WeakReference;

import quicktfs.apiclients.contracts.exceptions.ApiAccessException;

/**
 * Base implementation for asynchronous task that use ApiClients for the TFS Api.
 * @param <TContext> Type of the context in which the asynchronous task is used.
 * @param <TParams> Type of the parameters of the asynchronous task.
 * @param <TResult> Type of the result of the asynchronous task.
 */
public abstract class AsyncApiClientTask<TContext extends Context, TParams, TResult>
        extends AsyncTask<TParams, Void, AsyncApiClientTask.ApiActionResult<TParams, TResult>> {

    // Weak reference to the context of the task.
    private final WeakReference<TContext> context;

    /**
     * Creates an AsyncApiClientTask.
     * @param context Context of the task.
     */
    protected AsyncApiClientTask(TContext context) {
        this.context = new WeakReference<>(context);
    }

    @Override
    protected final ApiActionResult<TParams, TResult> doInBackground(TParams[] params) {
        // Derived tasks should define a model for the expected parameters
        // which is thereby limited to one model per execution.
        if (params == null || params.length != 1) {
            throw new IllegalArgumentException("params");
        }

        try {
            return new ApiActionResult<>(params[0], doApiAction(params[0]));
        }
        catch(ApiAccessException exception) {
            return new ApiActionResult<>(params[0], exception);
        }
    }

    @Override
    protected final void onPostExecute(ApiActionResult<TParams, TResult> result) {
        handleComplete(result.getParams());

        if (result.wasSuccessful()) {
            handleSuccess(result.getParams(), result.getApiResult());
        }
        else {
            handleApiAccessException(result.getParams(), result.getApiAccessException());
        }
    }

    /**
     * Gets the context of the asynchronous task.
     * @return The context; or null if it is no longer available.
     */
    protected final TContext getContext() { return context.get(); }

    /**
     * Handles exceptions that occur by accessing the TFS Api (e.g. network problems).
     * @param params Parameters that were passed to the task.
     * @param exception Exception that was thrown.
     */
    protected void handleApiAccessException(TParams params, ApiAccessException exception) {
        Context ctx = getContext();
        if (ctx == null) return;

        Toast.makeText(ctx, ctx.getText(R.string.apiError) + exception.getLocalizedMessage(), Toast.LENGTH_LONG).show();
    }

    /**
     * Should be overridden to define the actual operation with Api access.
     * @param params Parameter that was specified for the execution.
     * @return The result of the operation.
     */
    protected abstract TResult doApiAction(TParams params) throws ApiAccessException;

    /**
     * Should be overridden to define the handling of a successful operation.
     * @param params Parameters that were passed to the task.
     * @param result Result of the operation.
     */
    protected abstract void handleSuccess(TParams params, TResult result);

    /**
     * Should be overridden to define the handling of completion of the operation.
     * Will be executed in success and failure cases.
     * @param params Parameters that were passed to the task.
     */
    protected void handleComplete(TParams params) { }

    /**
     * Models the result of an action with Api access.
     * This can be either successful (with the result of the action)
     * or failed (without result, but an ApiAccessException).
     */
    static final class ApiActionResult<TParams, TResult> {
        private final ApiAccessException exception;
        private final TParams params;
        private final TResult result;

        /**
         * Creates an ApiActionResult for a successful operation.
         * @param params Parameters that were passed to the task.
         * @param result The result was generated by the operation.
         */
        ApiActionResult(TParams params, TResult result) {
            this.params = params;
            this.result = result;
            this.exception = null;
        }

        /**
         * Creates an ApiActionResult for a failed operation.
         * @param params Parameters that were passed to the task.
         * @param exception The exception that was thrown during the operation.
         */
        ApiActionResult(TParams params, ApiAccessException exception) {
            this.params = params;
            this.result = null;
            this.exception = exception;
        }

        /**
         * Indicates if the operation was successful.
         * @return True, if the operation was successful; otherwise false.
         */
        boolean wasSuccessful() { return exception == null; }

        /**
         * Gets the parameters that were passed to the task.
         * @return The parameters that were passed to the task.
         */
        TParams getParams() { return params; }

        /**
         * Gets the result of a successful operation.
         * @return The result of the operation; or null if it was not successful.
         */
        TResult getApiResult() { return result; }

        /**
         * Gets the exception thrown by a failed operation.
         * @return The exception thrown by a failed operation; or null if it was successful.
         */
        ApiAccessException getApiAccessException() { return exception; }
    }
}